FROM nginx

RUN mkdir /etc/nginx/cache
COPY nginx.conf /etc/nginx/nginx.conf
COPY fullchain.pem /etc/letsencrypt/live/give928.kro.kr/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/give928.kro.kr/privkey.pem
